[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/amp"
  to = "/.netlify/functions/amp"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200
