[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/amp"
  to = "/.netlify/functions/amp"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/engine"
  to = "/.netlify/functions/engine"
  status = 200

[[redirects]]
  from = "/decode"
  to = "/.netlify/functions/decode"
  status = 200
